- hosts: localhost
  # vars:
  #   source_key: "./.ssh/id_rsa"
  #   dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  #   personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Ensure brew requirements are met
    homebrew:
      name: "{{ item }}"
      state: present
    with_items:
      - gnu-tar
  tasks:
    - include: tasks/fonts.yml
    # - include: tasks/mac-settings.yml