- hosts: localhost
  vars:
    source_key: "./ssh/id_github"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_github"
  pre_tasks:
  - name: Brew Update
    community.general.homebrew:
      update_homebrew: true
      upgrade_all: true
  tasks:
    - include: tasks/fonts.yml
    - include: tasks/programs.yml
    - include: tasks/dock.yml
    - include: tasks/mac-settings.yml
    - include: tasks/ssh.yml