- name: Programs | Installing stow
  community.general.homebrew:
    name:
      - stow
  tags:
    - dotfiles
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:PearceKieser/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
    key_file: "{{ dest_key }}"
  tags:
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./macos.zsh
  tags:
    - dotfiles