# TODO fix dict -> Unhashable type issue here https://github.com/ansible-collections/community.general/blob/main/plugins/modules/osx_defaults.py#L348

# - name: "Mac Settings | keyboard fixes"
#   community.general.osx_defaults:
#     domain: "Apple Global Domain"
#     key: com.apple.keyboard.modifiermapping.1452-834-0
#     host: currentHost
#     type: array
#     value: 
#       - HIDKeyboardModifierMappingDst: 30064771113
#         HIDKeyboardModifierMappingSrc: 30064771129

- name: Mac Settings | Brew Install defaultbrowser
  community.general.homebrew_cask:
    name: defaultbrowser
    state: present
- name: Mac Settings | defaultbrowser chrome
  shell: defaultbrowser chrome
- name: "Mac Settings | dark mode"
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: AppleInterfaceStyle
    type: string
    value: Dark
- name: "Mac Settings | Disable natural scroll"
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: "com.apple.swipescrolldirection"
    type: boolean
    value: false
- name: "Mac Settings | touch pad sensitivity"
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: "com.apple.trackpad.scaling"
    type: float
    value: 0.125
# TODO use com.apple.ncprefs to set the notification visibility - use flags between bundle-id and path
# 41951246 -> 8396614
- name: "Mac Settings | dock autohide"
  community.general.osx_defaults:
    domain: "com.apple.dock"
    key: "autohide"
    type: boolean
    value: true
- name: "Mac Settings | dock show recent apps"
  community.general.osx_defaults:
    domain: "com.apple.dock"
    key: "show-recents"
    type: boolean
    value: true