- name: "Mac Settings | keyboard fixes"
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: com.apple.keyboard.modifiermapping.1452-834-0
    host: currentHost
    type: string
    value: |
        (
          {
            HIDKeyboardModifierMappingDst = 30064771113;
            HIDKeyboardModifierMappingSrc = 30064771129;
          }
        )