- name: Programs | Install Brew Formulas
  community.general.homebrew:
    name:
      # JAVA
      - maven
      - gradle
      # TS/JS
      - npm
      - pnpm
      - "n" 
      - node
      # Ruby
      # - ruby@3.2
      # Terminal
      - tmux
      - neovim
      - jq
      # CLI helpers
      - fzf
      - ripgrep
      - tldr
      - gh
      - yt-dlp
      - delta
      # Utilities
      - wireshark
- name: Programs | Install Brew Casks
  community.general.homebrew_cask:
    name: 
      # IDE
      - visual-studio-code
      - intellij-idea-ce
      # Terminal
      - iterm2
      - raycast
      # Browser
      - google-chrome
      - firefox
      # Chat
      - slack
      - amazon-chime
      # Tools
      - docker
      # JAVA
      - "homebrew/cask-versions/corretto8" # would be better if versioned like node https://github.com/corretto/corretto-8/issues/42
      - "homebrew/cask-versions/corretto11"
      - "homebrew/cask-versions/corretto17"
      # Python
      - miniconda
      # Music
      - spotify
      # Window manager
      - rectangle
      # Utilities
      - wireshark
      - calibre
      # TODO include office and onedrive if personal is true
    state: present
