- name: Programs | Install Brew Formulas
  community.general.homebrew:
    name:
      # JAVA
      - maven
      - gradle
      # TS/JS
      - npm
      - pnpm
      - "n" 
      - node@18 
      - node@16
      - node@14
      # Terminal
      - tmux
      - neovim
      - jq
      # Productivity
      - fzf
      - wireshark
      - ripgrep
      - tldr
      - gh
- name: Programs | Install Brew Casks
  community.general.homebrew_cask:
    name: 
      # IDE
      - visual-studio-code
      - intellij-idea-ce
      # Terminal
      - iterm2
      # Browser
      - google-chrome
      - firefox
      # Chat
      - slack
      - amazon-chime
      # Tools
      - docker
      # JAVA
      - "homebrew/cask-versions/corretto8" # would be better if versioned like node https://github.com/corretto/corretto-8/issues/42
      - "homebrew/cask-versions/corretto11"
      - "homebrew/cask-versions/corretto17"
      # Music
      - spotify
      # TODO include office and onedrive if personal is true
    state: present