- name: Programs | Install Programs
  community.general.homebrew_cask:
    name: 
      - visual-studio-code
      - intellij-idea-ce
      - iterm2
      - google-chrome
      - firefox
      - slack
      - docker
      - amazon-chime
      # JAVA
      - maven
      - gradle
      - "homebrew/cask-versions/corretto8" # would be better if versioned like node https://github.com/corretto/corretto-8/issues/42
      - "homebrew/cask-versions/corretto11"
      - "homebrew/cask-versions/corretto17"
      # TS/JS
      - npm
      - pnpm
      - "n" 
      - node@16
      - node@14
      - node@12
      # TODO include office and onedrive if personal is true
    state: present